blog_avg/blog/urls.py
from django.urls import path
from blog.views import(
    create_blog_view,
    detail_blog_view,
    edit_blog_view,
    comment_submit,
    like_post,
    subscribe,
    get_author_info,
    approve_blog_post_view,
    in_review_blog_view
)

app_name= 'blog'

urlpatterns =[
    path('create/', create_blog_view, name='create'),
    path('subscribe/', subscribe, name='subscribe'),
    path('get_author_info/', get_author_info, name='get_author_info'),
    path('in_review_posts/', in_review_blog_view, name='in_review_posts'),


    path('<slug>/', detail_blog_view, name='detail'),
    path('<slug>/edit', edit_blog_view, name='edit'),
    path('<slug>/comment/submit/', comment_submit, name='comment_submit'),
    path('<slug>/like/', like_post, name='like_post'),
    path('<slug>/approve_blog_post/', approve_blog_post_view, name='approve_blog_post'),

]

blog_avg/blog_avg/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from personal.views import (home_screen_view,about_view, contact_view, send_email)
from account.views import (registration_view, 
logout_view, 
login_view,
profile_view,
must_authenticate_view,
)


urlpatterns = [
    path('', home_screen_view, name='home'),
    path('about/', about_view, name='about'),
    path('contact/', contact_view, name='contact'),
    path('send_email/', send_email, name='send_email'),

    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls', 'blog')),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('profile/', profile_view, name="profile"),
    path('register/', registration_view, name="register"),
    path('ckeditor/', include('ckeditor_uploader.urls')),


    #Password reset link views
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_avg/templates/snippets/base_css.html
<style>
    body{
        background-color: #fffffffd;
        
    }
    h1{
        margin-top: 30px;
    }
    button{
        background-color:  rgb(214, 22, 111);;
    }
</style>

blog_avg/templates/snippets/footer.html
<style type="text/css">

.footer{
    min-height: 100px;
}

</style>

<!--Footer-->
<div class="d-flex flex-row align-items-center footer m-auto bg-dark bg-gradient border-top shadow-lg">
    <p class="m-auto text-white">Bubble Of Thoughts</p>
</div>
<!--END Footer-->



<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

blog_avg/templates/snippets/header.html
{% load static %}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
<style>
    .form-control-dark {
  border-color: var(--bs-gray);
}
.form-control-dark:focus {
  border-color: #fff;
  box-shadow: 0 0 0 .25rem rgba(255, 255, 255, .25);
}

.text-small {
  font-size: 85%;
  color:aliceblue;
}

.dropdown-toggle {
  outline: 0;
}

.header_color{
  background-color: #06052e;
  color:#fff;
}

.search-bar{
 max-width: 500px;
 width: 100% 
} 
/* Increase specificity for primary buttons */
    a[href*="{% url 'register' %}"] .btn-primary {
        background-color:rgb(233, 62, 62); /* Pink color */
        border-color:   rgb(233, 62, 62);
    }

    /* Increase specificity for outline-primary buttons */
    a[href*="{% url 'login' %}"] .btn-outline-primary {
        color: rgb(233, 62, 62);/* Pink color */
        border-color:rgb(233, 62, 62);
    }
</style>
<div>
<div class="container">
  <div class="row" style="background-color:  rgb(255, 121, 111);">
  <div class="left-column col-lg-2 p-0"> 
    <a href="{% url 'home' %}" >    
      <img src="{% static 'bubble-of-thoughts-high-resolution-logo-black-on-transparent-background.svg' %}" alt="Bubble of Thoughts" width="100%" style="max-height: 200px; max-width: 200px;"> 
    </a>
  </div>
  <!-- <div class="left-column col-lg-10 p-0">
    <img src="{% static 'Bubble of Thoughts theme.png' %}" alt="Bubble of Thoughts theme" width="100%" height="200px"> 
  </div> -->
</div>
</div>
<div class="container p-0">
<div class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-0 border-bottom shadow-sm header_color">

    <ul class="nav col-12 col-md-auto justify-content-center mb-md-0 m-auto">
        <li><a href="{% url 'home' %}" class="nav-link link-light px-2 link-secondary">Home</a></li>
        <li><a href="{% url 'about' %}" class="nav-link link-light px-2 link-secondary">About</a></li>
        <li><a href="{% url 'contact' %}" class="nav-link link-light px-2 link-secondary">Contact</a></li>
    </ul>
      
    <div class="search-bar mt-sm-2 mr-2">
      <form method="get" role="search">{% csrf_token %}
        <input type="text" class="form-control" name="q" id= "id_q" placeholder="Search..." value="{{query}}">
      </form>
    </div>

    {% if request.user.is_authenticated %}
        
            <div class="dropdown text-end">
              <a href="#" class="d-block link-light text-decoration-none dropdown-toggle px-2" data-bs-toggle="dropdown" aria-expanded="false">{{request.user.username}}</a>
              <ul class="dropdown-menu text-small">
                <li><a class="dropdown-item" href="#">Update DP</a></li>
                <li><a class="dropdown-item" href="{% url 'profile' %}">Profile</a></li>
                {% if request.user.is_writer %}
                <li><a class="dropdown-item" href="{% url 'blog:create' %}">Write a new Blog Post</a></li>
                {% endif %}
                {% if request.user.is_editor %}
                <li><a class="dropdown-item" href="{% url 'blog:in_review_posts' %}">Review Guest Blogs</a></li>
                {% endif %}
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'logout' %}">Sign out</a></li>
              </ul>
            </div>        
    {% else %}
        <div class="col-md-3 text-end">
            <a href ="{% url 'login' %}" style="margin-right: 10px;"><button type="button" class="btn btn-outline-primary me-2">Login</button></a>
            <a href ="{% url 'register' %}"  style="margin-right: 10px;"><button type="button" class="btn btn-primary">Sign-up</button></a>
        </div>
        <!-- Need to add js logic to handle buttons colors -->
    {% endif %}
</div>
</div>
</div>