blog_avg/blog/urls.py
from django.urls import path
from blog.views import(
    create_blog_view,
    detail_blog_view,
    edit_blog_view,
    comment_submit,
    like_post,
    subscribe,
    get_author_info,
    approve_blog_post_view,
    in_review_blog_view
)

app_name= 'blog'

urlpatterns =[
    path('create/', create_blog_view, name='create'),
    path('subscribe/', subscribe, name='subscribe'),
    path('get_author_info/', get_author_info, name='get_author_info'),
    path('in_review_posts/', in_review_blog_view, name='in_review_posts'),


    path('<slug>/', detail_blog_view, name='detail'),
    path('<slug>/edit', edit_blog_view, name='edit'),
    path('<slug>/comment/submit/', comment_submit, name='comment_submit'),
    path('<slug>/like/', like_post, name='like_post'),
    path('<slug>/approve_blog_post/', approve_blog_post_view, name='approve_blog_post'),

]

blog_avg/blog_avg/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from personal.views import (home_screen_view,about_view, contact_view, send_email)
from account.views import (registration_view, 
logout_view, 
login_view,
profile_view,
must_authenticate_view,
)


urlpatterns = [
    path('', home_screen_view, name='home'),
    path('about/', about_view, name='about'),
    path('contact/', contact_view, name='contact'),
    path('send_email/', send_email, name='send_email'),

    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls', 'blog')),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('profile/', profile_view, name="profile"),
    path('register/', registration_view, name="register"),
    path('ckeditor/', include('ckeditor_uploader.urls')),


    #Password reset link views
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_avg/personal/models.py
from django.db import models

# Create your models here.
Priority=[ ("L","Low"), ("M", "Medium"), ("H", "High") ]

#class Question(models.Model):
 #   title= models.CharField(max_length=60)
 #   question= models.TextField(max_length=400)
 #   priority=models.CharField(max_length=1, choices=Priority)
#
 #   def __str__(self):
  #      return self.title
 #   class Meta:
 #       verbose_name="The Question"
 #       verbose_name_plural="People Questions"

blog_avg/personal/views.py
from django.shortcuts import render
from operator import attrgetter
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.http import JsonResponse
import requests
from dotenv import load_dotenv
import os

from blog.views import get_blog_queryset, get_popular_blogs, subscribe
from .mail_module import send_mail
from blog.forms import SubscriberForm

# Create your views here.
BLOG_POSTS_PER_PAGE=10

BODY_MESSAGE_FROM_USER = """  
        <div style="max-width: 600px; margin: 20px auto; background-color: #fff; padding: 20px; border-radius: 8px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);">
            <p>Hello Bubble Of Thoughts,</p>
            <p>You got a new message from {0}:</p>
            <div style="border-left: 4px solid #007bff; padding: 12px; font-style: italic; margin-top: 20px;">
                <p style="margin: 0; padding: 0;">
                    {1}
                </p>
            </div>
            <p style="margin-top: 20px; font-style: italic; color: #555;">Best wishes,<br>{0}</p>
        </div>
    """
CONFIRM_MESSAGE_TEMPLATE_FROM_SERVER = """
<div style="max-width: 600px; margin: 20px auto; background-color: #fff; padding: 20px; border-radius: 8px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);">
            <p>Hello {0},</p>
            <p>Your following message has been delivered to us, and we will soon respond.</p>
            <div style="border-left: 4px solid #007bff; padding: 12px; font-style: italic; margin-top: 20px;">
                <p style="margin: 0; padding: 0;">
                    {1}
                </p>
            </div>
            <p style="margin-top: 20px; font-style: italic; color: #555;">Best wishes,<br>Anugrah Gupta</p>
        </div>
"""

def home_screen_view(request, context={}):

    query =""
    
    if request.GET:
        query=request.GET.get('q','')
        context['query'] = str(query)


    blog_posts = sorted(get_blog_queryset(query, status='published'), key= attrgetter('date_published'), reverse=True)

    #get top most popular blogs
    popular_posts= get_popular_blogs(blog_posts)

    #   Pagination
    page = request.GET.get('page', 1)
    blog_posts_paginator=Paginator(blog_posts, BLOG_POSTS_PER_PAGE)

    try:
        blog_posts = blog_posts_paginator.page(page)
    except PageNotAnInteger:
        blog_posts = blog_posts_paginator.page(BLOG_POSTS_PER_PAGE)
    except EmptyPage:
        blog_posts = blog_posts_paginator.page(blog_posts_paginator.num_pages)
        
    context['blog_posts']=blog_posts
    context['popular_posts']=popular_posts
    context['subscriber_form']=SubscriberForm()

    return render(request, 'personal/home.html',context)



def about_view(request):
    context={}
    return render(request, 'personal/about.html',context)



def contact_view(request):
    context={}
    
    return render(request, 'personal/contact.html',context)


def send_email(request):
    context={}

    if request.method == 'POST':
        load_dotenv()

        # Get form data
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')

        # Prepare data for Email.js template
        template_params = {
            'from_name': name,
            'reply_to': email,
            'message': message,
        }
        msg_body_from_user= BODY_MESSAGE_FROM_USER.format(template_params['from_name'], template_params['message'])
        msg_body_from_server= CONFIRM_MESSAGE_TEMPLATE_FROM_SERVER.format(template_params['from_name'], template_params['message'])

        # mail from user to my email
        result= send_mail(subject= 'Message from reader', msg_content=msg_body_from_user, from_name=template_params['from_name'], reply_to=template_params['reply_to'])
        # Send a Receipt mail to user
        result= send_mail(subject= 'We got your message', msg_content=msg_body_from_server, receiver=template_params['reply_to'], reply_to='bubbleofthought@outlook.com')

        # Check if the email was sent successfully
        if result:
            context['mail_status']='success'
        else:
            context['mail_status']='something went wrong, please check mail address again.'
    
        return render(request, 'personal/contact.html',context)

blog_avg/personal/templates/personal/snippets/body_snippet.html
{% load static %}

<div class="container p-0">
    {% if blog_posts %}
    
    <!--Popular Blog Posts-->
        <div> 
        {% include 'blog/snippets/popular_blog_posts.html' with popular_posts=popular_posts %}
        </div>
    <!--End Popular Blog Posts-->
<div class="row">
    <!-- Latest Blog posts-->
        <div>
            {% include 'blog/snippets/latest_post.html' with latest_posts=blog_posts %}
        </div>
    {% else %}
        <div class="blog-post-container">
            {% include 'blog/snippets/blog_post_snippet.html' with query=query%}
        </div>
    {% endif %}
</div>
    <!-- End Latest Blog posts-->
    
    <!--Pagination-->
    {% include 'blog/snippets/blog_post_pagination.html' with blog_posts=blog_posts%}
    <!--End Pagination-->

</div>

blog_avg/personal/templates/personal/snippets/right_side_snippet.html
{% load static %}

<style>
.sidebar {
  position: sticky;
  top: 0;
  right: 0;
  width: 80%;
  margin-left: 20%;
}


.email-subscriber {
  margin-bottom: 20px;
  margin-top: 20%;
}

.email-subscriber h3 {
  margin-bottom: 10px;
}

.email-subscriber input[type="email"],
.email-subscriber input[type="text"],
.email-subscriber button {
  padding: 10px;
  font-size: 16px;
  border-radius: 5px;
  border: none;
}

.email-subscriber input[type="email"] {
  width: 100%;
  margin-right: 10px;
}

.email-subscriber button {
  background-color: #0e162c;
  color: #fff;
  cursor: pointer;
}

.social-media h3 {
  margin-bottom: 10px;
}

.social-media ul {
  list-style: none;
  padding: 0;
  margin: 0;
  display: flex;
}

.social-media li {
  margin-right: 10px;
}

.social-media li:last-child {
  margin-right: 0;
}

.social-media a {
  color: #fff;
  font-size: 20px;
  display: block;
  height: 50px;
  width: 50px;
  background-color:#0e162c;
  text-align: center;
  line-height: 50px;
  border-radius: 50%;
  margin-bottom: 85px;
}
.email-input{
  background-color: rgb(193, 232, 255);
  border-style: none;
}
.name-input{
  background-color: rgb(193, 232, 255);
  border-style: none;
  margin-bottom:2px;
}
</style>

<div class="sidebar">
  <!-- Email Subscriber field -->
  <div class="email-subscriber">
      <h3>Subscribe to our newsletter</h3>
      <form id="subscribe-form" action="{% url 'blog:subscribe' %}" method="post">
          {% csrf_token %}
          <div class="form-group">
              {{ subscriber_form.name }}
              {{ subscriber_form.email }}
          </div>
          <button type="button" id="subscribe-button">Subscribe</button>
      </form>
  </div>

  <!-- Social media follow icons -->
  <div class="social-media">
      <h3>Follow us</h3>
      <ul>
          <li><a href="https://twitter.com/AnugrahGup430" target="_blank"><i class="fab fa-twitter"></i></a></li>
          <li><a href="https://www.instagram.com/bubbleofthoughts_official/" target="_blank"><i
                      class="fab fa-instagram"></i></a></li>
      </ul>
  </div>
</div>

<script>$(document).ready(function () {
  $('#subscribe-button').click(function () {
      $.ajax({
          type: 'POST',
          url: '{% url "blog:subscribe" %}',
          data: $('#subscribe-form').serialize(),
          success: function (response) {
            console.log($('#subscribe-form').serialize())
              if (response.success) {
                  console.log(response.message);
                  alert(response.message);
              } else {
                  alert(response.message);
                  // Output the errors to the console for debugging
                  console.log(response.errors);
              }
          }
      });
  });
});
</script>